### ISSUE TITLE
$.level should be writable

### ISSUE THREAD

**Issue by kitloong** [felixSchl/photoshop.d.ts#17]
Hi, in the official documentation [Photoshop CC Javascript Reference 2015](http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2015.pdf) page 132

`$.level = 1;`

indicating we can actually write into `$.level`.

I have a project depending overwriting the value of `$.level`

Can we remove the `readonly` from `extendscript/es.dollar.d.ts` line 93
`static readonly level: number`

**Comment by perludum** [comment]
Thanks for the hint!

The documentation for the dollar object in the [JavaScript Tools Guide CC](http://download.macromedia.com/pub/developer/aftereffects/scripting/JavaScript-Tools-Guide-CC.pdf) declared it as readonly, but you're right, I've also seen it being used to set the debug level with it.

Fixed in https://github.com/felixSchl/photoshop.d.ts/commit/41b1d9ca76451eddf8ee26007d212788dc8c274b

**Comment by kitloong** [comment]
Thank you!
